###
# This file defines some constants for various things such as colour, status, etc.
###

COLOUR_BLUE = 1
COLOUR_ORANGE = 2
COLOUR_PINK = 3
COLOUR_PURPLE = 4
COLOUR_WHITE = 5
COLOUR_YELLOW = 6

# Not-colours, for problem confront requirements
COLOUR_NOT_BLUE = 7
COLOUR_NOT_ORANGE = 8
COLOUR_NOT_PINK = 9
COLOUR_NOT_PURPLE = 10
COLOUR_NOT_WHITE = 11
COLOUR_NOT_YELLOW = 12

STATUS_READY = 1
STATUS_EXHAUSTED = 2
STATUS_SUPER_EXHAUSTED = 3
STATUS_FRIGHTENED = 4

AREA_ACTIVE_HOME = 1
AREA_NONACTIVE_HOME = 2
AREA_ACTIVE_PROBLEM = 3
AREA_NONACTIVE_PROBLEM = 4

SET_PREMIER = 1
SET_CANTERLOT_NIGHTS = 2
SET_ROCK_AND_RAVE = 3
SET_CELESTIAL_SOLSTICE = 4
SET_CRYSTAL_GAMES = 5
SET_PROMOTIONAL = 6
SET_ABSOLUTE_DISCORD = 7
SET_EQUESTRIAN_ODYSSEYS = 8
SET_HIGH_MAGIC = 9
SET_SANDS_OF_TIME = 10
SET_MARKS_IN_TIME = 11
SET_DEFENDERS_OF_EQUESTRIA = 12
SET_SEAQUESTRIA_AND_BEYOND = 13